import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Zap, Database, Shield, CreditCard, GitBranch, Cloud } from 'lucide-react';

const Home = () => {
  return (
    <div className="flex flex-col items-center">
      
      {/* Hero Section */}
      <section className="py-24 flex flex-col items-center text-center px-4 max-w-4xl w-full">
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 leading-tight text-light-text dark:text-dark-text">
          Ship your vision <br className="hidden sm:block" />
          <span className="text-primary-500">in minutes, not weeks.</span>
        </h1>
        <p className="text-lg md:text-xl text-light-textMuted dark:text-dark-textMuted max-w-2xl mb-10">
          The all-in-one full-stack boilerplate generator for modern web apps. Build your next idea with instant setup and supreme configuration.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center gap-4 w-full max-w-md">
          <Link to="/generate" className="btn-primary flex items-center justify-center gap-2 w-full py-4 text-lg">
            Generate Stack <ArrowRight className="w-5 h-5" />
          </Link>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mt-16 w-full max-w-3xl border-t border-light-border dark:border-dark-border pt-12">
          <div className="flex flex-col items-center">
            <h3 className="text-3xl font-bold text-primary-500 mb-2">3+</h3>
            <p className="text-sm text-light-textMuted dark:text-dark-textMuted font-medium tracking-wide uppercase">Stacks Supported</p>
          </div>
          <div className="flex flex-col items-center">
            <h3 className="text-3xl font-bold text-primary-500 mb-2">90%</h3>
            <p className="text-sm text-light-textMuted dark:text-dark-textMuted font-medium tracking-wide uppercase">Time Saved</p>
          </div>
          <div className="flex flex-col items-center">
            <h3 className="text-3xl font-bold text-primary-500 mb-2">&lt; 5<span className="text-xl">min</span></h3>
            <p className="text-sm text-light-textMuted dark:text-dark-textMuted font-medium tracking-wide uppercase">Setup Time</p>
          </div>
          <div className="flex flex-col items-center">
            <h3 className="text-3xl font-bold text-primary-500 mb-2">100%</h3>
            <p className="text-sm text-light-textMuted dark:text-dark-textMuted font-medium tracking-wide uppercase">Open Source</p>
          </div>
        </div>
      </section>

      {/* Code Preview Image Placeholder */}
      <section className="w-full max-w-5xl px-4 py-8 mb-16">
        <div className="w-full h-[400px] bg-dark-bg border border-dark-border rounded-xl shadow-2xl relative overflow-hidden flex flex-col">
          <div className="h-10 bg-[#1e293b] flex items-center px-4 gap-2">
            <div className="w-3 h-3 rounded-full bg-red-500"></div>
            <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
            <div className="w-3 h-3 rounded-full bg-green-500"></div>
          </div>
          <div className="p-6 text-sm font-mono text-green-400 opacity-90 leading-relaxed overflow-hidden">
            <p><span className="text-blue-400">import</span> React <span className="text-blue-400">from</span> 'react';</p>
            <p><span className="text-blue-400">import</span> express <span className="text-blue-400">from</span> 'express';</p>
            <p><span className="text-blue-400">import</span> mongoose <span className="text-blue-400">from</span> 'mongoose';</p>
            <br/>
            <p className="text-gray-500">// Auto-generated by MicroStack Builder</p>
            <p><span className="text-purple-400">const</span> app = <span className="text-yellow-200">express</span>();</p>
            <p>mongoose.<span className="text-yellow-200">connect</span>(process.env.<span className="text-teal-300">MONGO_URI</span>);</p>
            <br/>
            <p>app.<span className="text-yellow-200">listen</span>(5000, () <span className="text-blue-400">=&gt;</span> console.<span className="text-yellow-200">log</span>(<span className="text-orange-300">'Server running...'</span>));</p>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 max-w-6xl w-full">
        <div className="text-center mb-16">
          <h2 className="text-primary-500 font-bold uppercase tracking-wider text-sm mb-3">Everything you need</h2>
          <h3 className="text-3xl md:text-5xl font-bold text-light-text dark:text-dark-text">Full-stack infrastructure, on demand.</h3>
          <p className="mt-4 text-light-textMuted dark:text-dark-textMuted max-w-2xl mx-auto">Stop writing boilerplate code. Set up your authentication, database connection, routing, and deployment workflow with a single click.</p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <FeatureCard 
            icon={<Zap className="w-6 h-6" />}
            title="Instant Setup"
            desc="Get a fully functional full-stack project in seconds. Zero configuration needed before you start coding."
          />
          <FeatureCard 
            icon={<Database className="w-6 h-6" />}
            title="Database Ready"
            desc="Out-of-the-box Mongoose models or Prisma schemas configured for MongoDB or PostgreSQL."
          />
          <FeatureCard 
            icon={<Shield className="w-6 h-6" />}
            title="API & Auth Built-in"
            desc="Secure JWT authentication, password hashing, and protected route middleware pre-configured."
          />
          <FeatureCard 
            icon={<CreditCard className="w-6 h-6" />}
            title="Modern Architectures"
            desc="Choose between monolithic MVC or microservices pattern tailored for your scalability needs."
          />
          <FeatureCard 
            icon={<GitBranch className="w-6 h-6" />}
            title="CI/CD Workflows"
            desc="Automated GitHub Actions setup for tests, linting, and building your application pipeline."
          />
          <FeatureCard 
            icon={<Cloud className="w-6 h-6" />}
            title="Auto Deployments"
            desc="Dockerfile and docker-compose.yml ready to spin up your application container instantly."
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 w-full px-4 mb-10">
        <div className="max-w-4xl mx-auto bg-primary-500 text-white rounded-3xl p-10 md:p-16 text-center shadow-xl relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-white/20 to-transparent"></div>
          <h2 className="text-3xl md:text-5xl font-bold mb-6 relative z-10">Ready to build your next big idea?</h2>
          <p className="text-primary-100 text-lg mb-10 max-w-2xl mx-auto relative z-10">Join thousands of developers using MicroStack Builder to save hundreds of hours of configuration.</p>
          <Link to="/register" className="inline-block bg-white text-primary-600 font-bold text-lg px-8 py-4 rounded-xl shadow-lg hover:bg-slate-50 transition-colors relative z-10">
            Get Started For Free
          </Link>
        </div>
      </section>

    </div>
  );
};

const FeatureCard = ({ icon, title, desc }) => (
  <div className="card p-8 hover:-translate-y-1 transition-transform duration-300 relative overflow-hidden group">
    <div className="w-12 h-12 bg-primary-100 dark:bg-primary-900/50 text-primary-500 rounded-xl flex items-center justify-center mb-6 relative z-10">
      {icon}
    </div>
    <h4 className="text-xl font-bold text-light-text dark:text-dark-text mb-3 relative z-10">{title}</h4>
    <p className="text-light-textMuted dark:text-dark-textMuted leading-relaxed relative z-10">{desc}</p>
    <div className="absolute -bottom-2 -right-2 w-24 h-24 bg-primary-500/5 dark:bg-primary-500/10 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
  </div>
);

export default Home;
